# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: lalithsuresh/dcm-ci-latest

    working_directory: ~/dcm

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # run tests!
      - run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package 
      - run: mvn -pl '!build-common' jacoco:report
      - run: bash <(curl -s https://codecov.io/bash)
